version: '2'
services:

  f6bb-web:
    depends_on:
      - f6bb-db
    build: .
    container_name: f6bb-web
    image: "744241446859.dkr.ecr.us-east-1.amazonaws.com/foundation-6-bones-bootstrap:latest"
    # image: "realinteractive/f6bb-web"
    ports:
      - "80:80"
    links:
      - f6bb-db
    volumes:
      - ./deploy:/public_html
    restart: always

  f6bb-db:
    container_name: f6bb-db
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: H#8Et%xj@i%
      MYSQL_DATABASE: f6bb_website
      MYSQL_USER: f6bb
      MYSQL_PASSWORD: N#skj&98SR%Jje
